### ISSUE TITLE
Provide more documentation on how to set up installation medium

### ISSUE THREAD

**Issue by Abdull** [th-wilde/veracrypt-w10-patcher#10]
Right now I don't understand how to use the patcher. Should I create an ISO image with the Microsoft Media Creation Tool, then extract that ISO, then follow the instructions in the README?

**Comment by ataylor32** [comment]
These are the steps that worked for me:

1. Download [the media creation tool](https://www.microsoft.com/en-us/software-download/windows10)

1. Use the media creation tool to create an ISO

1. Extract the ISO somewhere on your HDD/SSD

1. Place [this repository's "veracrypt-w10-patcher.cmd" script](https://raw.githubusercontent.com/th-wilde/veracrypt-w10-patcher/master/veracrypt-w10-patcher.cmd) into the same folder where you extracted the ISO

1. Right-click the "veracrypt-w10-patcher.cmd" script and choose "Run as administrator"

1. After the script is finished, it will tell you to start the Windows 10 upgrade by executing setup.exe manually. Go ahead and do that.

Also, see [this comment](https://github.com/th-wilde/veracrypt-w10-patcher/issues/2#issuecomment-360564509).

**Comment by reillychase** [comment]
Video walkthrough of install media setup

https://www.youtube.com/watch?v=B55XVjXbFLA&lc=z22vctoh5onoxjgg004t1aokgqoxmesba3csci5utwcxbk0h00410.1526868346036314

@ 4:15

**Comment by th-wilde** [comment]
@Abdull This tool/readme primarily addresses experienced users and administrators. I tried to make it accessible with a video, but please keep in mind that upgrading this way is still risky. If it is to hard to understand, maybe you should ask someone else to help. Or choose the safe (and official) way by decrypting, upgrading and encrypting again.
