### ISSUE TITLE
How to update the script to make it work with Truecrypt? Can somebody help please?

### ISSUE THREAD

**Issue by dob636** [th-wilde/veracrypt-w10-patcher#11]
Dear community,

I'm new here and I registered because of the script you created. I have this issue for a long time now and because of this my Windows is absolutely outdated. I saw in the "Hall of Fame" that the user "ddumitriu"  (@ddumitriu) updated the script so it worked with his Truecrypt encrypted system drive and I would like to know if somebody could explain, what I need to change to get it to work like that?

The comment was [here](https://github.com/th-wilde/veracrypt-w10-patcher/issues/2#issuecomment-351993625).

I didn't find a option to contact the user with a private message or something and I'd really appreciate if somebody here could help me with that. Thanks for the great work you did with this script and thanks in advance if somebody can tell me what to do.

Have a nice day and kind regards

**Comment by denizdogan** [comment]
If I understand the comment correctly, @ddumitriu used a normal text editor (Notepad will do), opened the .cmd file which performs the patching in the editor and then replaced all instances of "VeraCrypt" with "TrueCrypt", "veracrypt" with "truecrypt", etc. N.B. I haven't done this myself, but that's what I think.

**Comment by drdcd** [comment]
That is correct.

**Comment by denizdogan** [comment]
I'm not sure if this has come up before, but maybe it would be a good idea to have a separate file for TrueCrypt named `truecrypt-w10-patcher.cmd`? Since they're virtually identical, this would make it much easier for users who aren't certain how to make the change themselves.

**Comment by dob636** [comment]
> I'm not sure if this has come up before, but maybe it would be a good idea to have a separate file for TrueCrypt named truecrypt-w10-patcher.cmd? Since they're virtually identical, this would make it much easier for users who aren't certain how to make the change themselves.
@denizdogan 

This would really help alot! It would be just perfect if anybody could do this.  @ddumitriu @denizdogan  @th-wilde 

Kind regards!

**Comment by drdcd** [comment]
I can issue a pull request, if wanted.

**Comment by dob636** [comment]
@ddumitriu This would be great! 
I saw this issue [here](https://github.com/th-wilde/veracrypt-w10-patcher/issues/13). This should work for TrueCrypt as well, what do you think? But in the TrueCrypt installation folder there are only .sys files and no .inf files as mentioned in the post. Do you know which files must be added to "SetupConfig.ini"?

Thanks for your help.

**Comment by th-wilde** [comment]
Hello,
i know it's a while but now i updated the README and accepted the pull request by @ddumitriu. So now TrueCrypt-Users also find a truecrypt-w10-patcher.cmd to patch their windows 10 medias for upgrades.

For VeraCrypt-Users there is now also a documentation about the ReflectDrivers/SetupConfig.ini mechanism and how they can get use of it with Veracrypt 1.23. TrueCrypt (since nobody maintains it more) will (probably) not work with this way of upgrading.
