### ISSUE TITLE
Patching Win 10 Creators Updates

### ISSUE THREAD

**Issue by noodles101** [th-wilde/veracrypt-w10-patcher#21]
Please make it possible to use it with Creators Updates.

They are stored local under c:\$WINDOWS.~BT\
![grafik](https://user-images.githubusercontent.com/6965320/41025478-3fe55bd2-6972-11e8-8e04-2250d7629bd0.png)

**Comment by th-wilde** [comment]
Is has been a wile but here is a answer:
The media patcher is not designed to work with the upgrades delivered by Windows Update. But the newly documentation ReflectDrivers-Method introduced by VeraCrypt Version 1.23 can deal with this. Check the updated README for more information.
