### ISSUE TITLE
Windows 10 Enterprise upgrade

### ISSUE THREAD

**Issue by satter** [th-wilde/veracrypt-w10-patcher#5]
I'm trying to upgrade my Win10 Ent install. I'm using rufus to create usb drive, as there is no Microsoft media tool for Ent edition.
The script is not working out of the box, it gives an error:
`dism Error: 0xc1420134`
`The drive of the specified mount path is not supported. Please mount to a volume on a fixed drive.`

**Comment by th-wilde** [comment]
Looks like you trying to patch directly on a FAT32 formatted USB-Device. This Error is related to the fact that the FAT32-Filesystem misses abilities that the dism-Tool uses to mount a WIM-Imagefile into a directory. The script creates a temporary folder in the folder/drive of the installation media to do the mounting and so the Filesystem of the location of the installation media matters. Also the install.wim Image file grows while patching and may breaks the 4GB file size limit of the FAT32-Filesystem.

Generally its a bad idea to patch the installation media on a USB-Device. USB-Devices can slow down the patching process if the read/write-Performance is low. (Usual bottlenacks are: cheap USB flash drives and a USB connectivity lower than 3.0).

Here is my recommendation for the patching process:
1. Get the **regular** install media from a suitable source.
2. Extract/Copy the files and folders of the ISO-Image/DVD-ROM/USB-flash-drive/... to a folder on a local (NTFS-Formatted) hard drive.
3. Place the script into the same folder on the local hard drive and run it as administrator.
4. The pathing should now work fine.
5. Run the Setup.exe from the folder on the local hard drive to start the upgrade-process and follow the instructions on the screen.

If you have to upgrade multiple machines: you can copy the patched installation media (after step 4) to a suitable media. A (NTFS-Formatted) USB-Device or even a network share will do the job. On the other machine just run the Setup.exe to start the upgrade.

If the machines runs a UEFI-Configuration of Windows and Veracrypt use a **regular** install media restore the required windows-bootloader entry on the NVRAM of the UEFI-Firmware **before you upgrade**. While the restored bootloader exist, make sure that the UEFI-Firmware boots the Veracrypt-Bootloader and not the restored windows-bootloader. The behavior depends on the UEFI-Firmware of your system. If the windows-bootloader entry causes any trouble (some UEFI-Firmewares seems to priorities always the windows-bootloader entry), you can remove it after the upgrade is done.

**Comment by satter** [comment]
> Looks like you trying to patch directly on a FAT32 formatted USB-Device.

Media creation tool uses FAT for Win10 usb drive which patches fine. I tried both FAT and NTFS filesystems in rufus: same error.
I will try your recommendation.
Thanks!

**Comment by satter** [comment]
I tried to update from local hdd and now windows is broken. After VC password prompt it just reboots, no errors, nothing.

**Comment by satter** [comment]
It seems was an UEFI/mobo (Supermicro X9DR3-F) issue. After white dots appears on windows startup my PC did reboot, so it was an endless loop. Even  Windows USB installation drives did behave same way.
I started VC recovery disk and decrypted system partition, it does not help. Only after complete poweroff (pull the AC plug) issue resolved and windows could continue updating.

So one having X9-generation Supermicro mobo with UEFI boot should proceed with caution. I think it's better to use decrypt-upgrade-encrypt approach.

**Comment by th-wilde** [comment]
Thanks for sharing your experience. I have still no idea what went wrong for you. Seems that some UEFI-Setups have more pitfalls than others. :/
