### ISSUE TITLE
Thanks for the veracrypt-w10-patcher

### ISSUE THREAD

**Issue by YwE9x** [th-wilde/veracrypt-w10-patcher#9]
This is an invention that I really need!

Everything went smooth until I started the setup.exe.

It took a while, then the Windows 10 installer asked for a product key - which I don't know because I got my  Windows 10 Pro 64-bit edition by download from Microsoft store - is there any way I can proceed?

**Comment by klaus7** [comment]
Enter in the command prompt: `wmic path SoftwareLicensingService get OA3xOriginalProductKey`

If you can't boot to windows anymore, use a bootable windows setup medium and hit SHIFT-F10.

**Comment by th-wilde** [comment]
@YwE9x i hope @klaus7's advice helped you. I think it's not related to the patcher. In general those upgrades of windows can cause all kinds of horrible and exotic problems. Even on a regular (not encrypted) system nobody can guarantee that everything goes smoothly.
